/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package baseTolkien.Window;

import baseTolkien.Controlador.BD;
import static baseTolkien.Controlador.BD.biblioteca;
import baseTolkien.Entidades.Aluno;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Eloigdn
 */
public class IUCadastroAluno extends javax.swing.JFrame {
  
    /**
     * Creates new form IUCadastroAluno
     */
    public IUCadastroAluno() {
        initComponents();
        this.msg_Label.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeAluno = new javax.swing.JLabel();
        nomeAluno_Text = new javax.swing.JTextField();
        jLabelCurso = new javax.swing.JLabel();
        curso_Text = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        ano_Text = new javax.swing.JTextField();
        jLabelCod = new javax.swing.JLabel();
        codigo_Text = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        msg_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNomeAluno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelNomeAluno.setText("Nome :");

        nomeAluno_Text.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nomeAluno_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAluno_TextActionPerformed(evt);
            }
        });

        jLabelCurso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCurso.setText("Curso :");

        curso_Text.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        curso_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curso_TextActionPerformed(evt);
            }
        });

        jLabelAno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelAno.setText("Ano :");

        ano_Text.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelCod.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCod.setText("Código :");

        codigo_Text.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jButtonSalvar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonSalvarFocusLost(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        msg_Label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        msg_Label.setForeground(new java.awt.Color(255, 0, 0));
        msg_Label.setText("Aluno Já Cadastrado!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCurso)
                                    .addComponent(jLabelNomeAluno))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeAluno_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(curso_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonCancelar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelAno)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ano_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(msg_Label)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeAluno)
                    .addComponent(nomeAluno_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCurso)
                    .addComponent(curso_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAno)
                    .addComponent(ano_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCod)
                    .addComponent(codigo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(msg_Label)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeAluno_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAluno_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAluno_TextActionPerformed

    private void curso_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curso_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curso_TextActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        String codUsuario = codigo_Text.getText();
        String nome = nomeAluno_Text.getText();
        String curso = curso_Text.getText();
        int ano = parseInt(ano_Text.getText());
        IUPrincipal.dataB.addAluno(codUsuario,nome,curso,ano);
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSalvarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalvarFocusLost
        String codUsuario = codigo_Text.getText();
        Aluno aluno = (Aluno) IUPrincipal.dataB.getUsuarioByCod(codUsuario);
        if(aluno != null){
            nomeAluno_Text.setText(aluno.getNome());
            codigo_Text.setText(codUsuario);
            curso_Text.setText(aluno.getCurso());
            ano_Text.setText(String.valueOf(aluno.getAno()));
            jButtonSalvar.setEnabled(false);
            this.msg_Label.setText("Aluno já Cadastrado!!!");
            this.msg_Label.setVisible(true);
            
        }
        else{
            nomeAluno_Text.setText("");
            curso_Text.setText("");
            ano_Text.setText("");
            jButtonSalvar.setEnabled(true);
            this.msg_Label.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonSalvarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUCadastroAluno().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano_Text;
    private javax.swing.JTextField codigo_Text;
    private javax.swing.JTextField curso_Text;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelNomeAluno;
    private javax.swing.JLabel msg_Label;
    private javax.swing.JTextField nomeAluno_Text;
    // End of variables declaration//GEN-END:variables
}
