/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package baseTolkien.Window;

import baseTolkien.Entidades.Livro;
import baseTolkien.Entidades.Relatorios.LivroRelatorio;
import baseTolkien.Entidades.Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eloigdn
 */
public class IUEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form IUEmprestimo
     */
    public IUEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUsuario = new javax.swing.JPanel();
        jLabelCodEmprestimo = new javax.swing.JLabel();
        codEmprestimo_Text = new javax.swing.JTextField();
        jLabelCodUsuario = new javax.swing.JLabel();
        codUsuario_Text = new javax.swing.JTextField();
        jLabelNomeUsuario = new javax.swing.JLabel();
        nomeUsuario_Text = new javax.swing.JTextField();
        jButtonLocalizarUsuario = new javax.swing.JButton();
        jLabelDataEmprestimo = new javax.swing.JLabel();
        dataEmprestimo_Text = new javax.swing.JTextField();
        jLabelDataDevolucao = new javax.swing.JLabel();
        dataDevolucao_Text = new javax.swing.JTextField();
        jPanelLivro = new javax.swing.JPanel();
        jLabelCodEmprestimo1 = new javax.swing.JLabel();
        codLivro_Text = new javax.swing.JTextField();
        jLabelNomeLivro = new javax.swing.JLabel();
        nomeLivro_Text = new javax.swing.JTextField();
        jButtonLocalizarLivro = new javax.swing.JButton();
        add_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), java.awt.Color.black)); // NOI18N

        jLabelCodEmprestimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelCodEmprestimo.setText("Codigo de Emprestimo");

        codEmprestimo_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabelCodUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelCodUsuario.setText("Codigo do Usuário");

        codUsuario_Text.setEditable(false);
        codUsuario_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabelNomeUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNomeUsuario.setText("Nome");

        nomeUsuario_Text.setEditable(false);
        nomeUsuario_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonLocalizarUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLocalizarUsuario.setText("Localizar");
        jButtonLocalizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarUsuarioActionPerformed(evt);
            }
        });

        jLabelDataEmprestimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelDataEmprestimo.setText("Data Empréstimo");

        dataEmprestimo_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataEmprestimo_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataEmprestimo_TextActionPerformed(evt);
            }
        });

        jLabelDataDevolucao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelDataDevolucao.setText("Data Devolução");

        dataDevolucao_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataDevolucao_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDevolucao_TextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(codUsuario_Text)
                    .addComponent(jLabelCodUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCodEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codEmprestimo_Text, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(39, 39, 39)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addComponent(nomeUsuario_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocalizarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeUsuario)
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabelDataEmprestimo)
                                .addGap(64, 64, 64)
                                .addComponent(jLabelDataDevolucao))
                            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                                .addComponent(dataEmprestimo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(dataDevolucao_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodEmprestimo)
                    .addComponent(jLabelDataEmprestimo)
                    .addComponent(jLabelDataDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codEmprestimo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataEmprestimo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDevolucao_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodUsuario)
                    .addComponent(jLabelNomeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codUsuario_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUsuario_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLocalizarUsuario))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jPanelLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), java.awt.Color.black)); // NOI18N

        jLabelCodEmprestimo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelCodEmprestimo1.setText("Codigo do Livro");

        codLivro_Text.setEditable(false);
        codLivro_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabelNomeLivro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNomeLivro.setText("Nome");

        nomeLivro_Text.setEditable(false);
        nomeLivro_Text.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButtonLocalizarLivro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLocalizarLivro.setText("Localizar");
        jButtonLocalizarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarLivroActionPerformed(evt);
            }
        });

        add_Button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        add_Button.setText("Adicionar");
        add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLivroLayout = new javax.swing.GroupLayout(jPanelLivro);
        jPanelLivro.setLayout(jPanelLivroLayout);
        jPanelLivroLayout.setHorizontalGroup(
            jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLivroLayout.createSequentialGroup()
                        .addGroup(jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodEmprestimo1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codLivro_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLivroLayout.createSequentialGroup()
                                .addComponent(nomeLivro_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLocalizarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelLivroLayout.createSequentialGroup()
                                .addComponent(jLabelNomeLivro)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLivroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLivroLayout.setVerticalGroup(
            jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLivroLayout.createSequentialGroup()
                .addGroup(jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodEmprestimo1)
                    .addComponent(jLabelNomeLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codLivro_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLivro_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLocalizarLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(add_Button))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livros do Empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jTableLivros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Livro", "Codigo do Livro", "Data do Empréstimo", "Data da Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLivros.setColumnSelectionAllowed(true);
        jTableLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLivros);
        jTableLivros.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableLivros.getColumnModel().getColumnCount() > 0) {
            jTableLivros.getColumnModel().getColumn(0).setResizable(false);
            jTableLivros.getColumnModel().getColumn(1).setResizable(false);
            jTableLivros.getColumnModel().getColumn(2).setResizable(false);
            jTableLivros.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLocalizarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarLivroActionPerformed
        IULocalizarLivro localiza = new IULocalizarLivro();
        localiza.setVisible(true);
        String codLivro = localiza.getCodigo();
        if (codLivro != null){
            Livro livro = IUPrincipal.dataB.getLivroByCod(codLivro);
            nomeUsuario_Text.setText(livro.getNome());
            codUsuario_Text.setText(codLivro);
        }
        localiza.dispose();
    }//GEN-LAST:event_jButtonLocalizarLivroActionPerformed

    private void dataEmprestimo_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataEmprestimo_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataEmprestimo_TextActionPerformed

    private void dataDevolucao_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDevolucao_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDevolucao_TextActionPerformed

    private void jButtonLocalizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarUsuarioActionPerformed
        
        IULocalizar localiza = new IULocalizar();
        localiza.setVisible(true);
        String codUsuario = localiza.getCodigo();
        if (codUsuario != null){
            Usuario user = IUPrincipal.dataB.getUsuarioByCod(codUsuario);
            nomeUsuario_Text.setText(user.getNome());
            codUsuario_Text.setText(codUsuario);
        }
        localiza.dispose();
    }//GEN-LAST:event_jButtonLocalizarUsuarioActionPerformed

    private void add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ButtonActionPerformed
       String nome = nomeLivro_Text.getText();
       String codLivro = codLivro_Text.getText();
       Object dataEmprest = (Object) dataEmprestimo_Text.getText();
       Object dataDevo = (Object) dataDevolucao_Text.getText();
       
       DefaultTableModel model = (DefaultTableModel) jTableLivros.getModel();
       Object[] linha = new Object[4];
       linha[0] = nome;
       linha[1] = codLivro;
       linha[2] = dataEmprest;
       linha[3] = dataDevo;
       model.addRow(linha);
       
    }//GEN-LAST:event_add_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_Button;
    private javax.swing.JTextField codEmprestimo_Text;
    private javax.swing.JTextField codLivro_Text;
    private javax.swing.JTextField codUsuario_Text;
    private javax.swing.JTextField dataDevolucao_Text;
    private javax.swing.JTextField dataEmprestimo_Text;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLocalizarLivro;
    private javax.swing.JButton jButtonLocalizarUsuario;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCodEmprestimo;
    private javax.swing.JLabel jLabelCodEmprestimo1;
    private javax.swing.JLabel jLabelCodUsuario;
    private javax.swing.JLabel jLabelDataDevolucao;
    private javax.swing.JLabel jLabelDataEmprestimo;
    private javax.swing.JLabel jLabelNomeLivro;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPanel jPanelLivro;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTextField nomeLivro_Text;
    private javax.swing.JTextField nomeUsuario_Text;
    // End of variables declaration//GEN-END:variables
}
