/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package baseTolkien.Window;

import baseTolkien.Controlador.BD;
import baseTolkien.Entidades.Emprestimo;
import baseTolkien.Entidades.Item;
import baseTolkien.Entidades.Livro;
import baseTolkien.Entidades.Relatorios.LivroRelatorio;
import baseTolkien.Entidades.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Dias
 */
public class IUSelecionarEmprestimo extends javax.swing.JFrame{

    ArrayList<LivroRelatorio> livros;
    ArrayList<LivroRelatorio> livrosEmprestimo;
    Usuario usuario;
    
    /**
     * Creates new form IUSelecionarEmprestimo
     */
    public IUSelecionarEmprestimo(Usuario usuario) {
        initComponents();
        setResizable(false);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.usuario = usuario;
        livrosEmprestimo = new ArrayList<LivroRelatorio>();
        model = (DefaultTableModel) jTableLivros.getModel();
        modelEmprestimo = (DefaultTableModel) jTableLivrosEmprestimo.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        btPesquisarNome = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        btConfirmarEmprestimo = new javax.swing.JButton();
        jLabelNome2 = new javax.swing.JLabel();
        btPesquisarCod = new javax.swing.JButton();
        jTextCodigo = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableLivrosEmprestimo = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelNome.setText("Nome:");

        btPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNomeActionPerformed(evt);
            }
        });

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableLivros);

        btConfirmarEmprestimo.setText("Confirmar Empréstimo");
        btConfirmarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarEmprestimoActionPerformed(evt);
            }
        });

        jLabelNome2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelNome2.setText("Código:");

        btPesquisarCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btPesquisarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCodActionPerformed(evt);
            }
        });

        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jTableLivrosEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableLivrosEmprestimo);

        btAdd.setText(">>");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btRemove.setText("<<");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome2)
                                    .addComponent(jLabelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(jTextNome)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPesquisarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(461, 461, 461))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAdd)
                                    .addComponent(btRemove))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConfirmarEmprestimo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome2)
                    .addComponent(btPesquisarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextCodigo)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNome)
                        .addComponent(jTextNome))
                    .addComponent(btPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemove))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConfirmarEmprestimo)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNomeActionPerformed
        if(livros!=null){
            livros.clear();
            while(model.getRowCount()>0)
            model.removeRow(0);
        }
        livros = BD.getLivroByNomeDisponivel(jTextNome.getText());
        
        for(int cont = 0; cont < livros.size();cont++){
            for(LivroRelatorio livro: livrosEmprestimo){
                if(livro.getCodLivro().equals((livros.get(cont).getCodLivro()))){
                    livros.remove(cont);
                    cont--;
                    break;
                }
            }
        }
        
        if(!livros.isEmpty())
            for(LivroRelatorio livro: livros){
                if(!livrosEmprestimo.contains(livro))
                    model.addRow(new Object[]{livro.getCodLivro(), livro.getNome()});
            }
    }//GEN-LAST:event_btPesquisarNomeActionPerformed

    private void btConfirmarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarEmprestimoActionPerformed
        if(!livrosEmprestimo.isEmpty()){
            Emprestimo emprestimo = new Emprestimo(BD.biblioteca.getConfiguracoes().getCodEmprestimo()+1+"", usuario);
            BD.biblioteca.getConfiguracoes().setCodEmprestimo(BD.biblioteca.getConfiguracoes().getCodEmprestimo()+1);
            for(int cont = 0; cont < livrosEmprestimo.size(); cont++){
                emprestimo.getItens().add(new Item(emprestimo.getCodEmprestimo(), livrosEmprestimo.get(cont).getCodLivro(), emprestimo.getDataDevolucao()));
                BD.emprestarLivro(livrosEmprestimo.get(cont).getCodLivro());
            }
            BD.biblioteca.addEmprestimo(emprestimo);
            dispose();
        }
    }//GEN-LAST:event_btConfirmarEmprestimoActionPerformed

    private void btPesquisarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCodActionPerformed
        if(livros!=null){
            livros.clear();
            while(model.getRowCount()>0)
            model.removeRow(0);
        }
        else{
            livros = new ArrayList<LivroRelatorio>();
        }
        LivroRelatorio livroTemp = BD.getLivroByCodDisponivel(jTextCodigo.getText());
        if(livroTemp!=null)
            livros.add(livroTemp);
        for(int cont = 0; cont < livros.size();cont++){
            for(LivroRelatorio livro: livrosEmprestimo){
                if(livro.getCodLivro().equals((livros.get(cont).getCodLivro()))){
                    livros.remove(cont);
                    cont--;
                    break;
                }
            }
        }
        if(!livros.isEmpty())
            for(LivroRelatorio livro: livros){
                model.addRow(new Object[]{livro.getCodLivro(), livro.getNome()});
            }
    }//GEN-LAST:event_btPesquisarCodActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        if(jTableLivros.getSelectedRow()!=-1){
                modelEmprestimo.addRow(new Object[]{livros.get(jTableLivros.getSelectedRow()).getCodLivro(),
                        livros.get(jTableLivros.getSelectedRow()).getNome()});
                livrosEmprestimo.add(livros.get(jTableLivros.getSelectedRow()));
                                livros.remove(jTableLivros.getSelectedRow());
                model.removeRow(jTableLivros.getSelectedRow());
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        if(jTableLivrosEmprestimo.getSelectedRow()!=-1){
            livros.add(livrosEmprestimo.get(jTableLivrosEmprestimo.getSelectedRow()));
            livrosEmprestimo.remove(jTableLivrosEmprestimo.getSelectedRow());
            modelEmprestimo.removeRow(jTableLivrosEmprestimo.getSelectedRow());
            while(model.getRowCount()>0)
                model.removeRow(0);
            if(!livros.isEmpty())
            for(LivroRelatorio livro: livros){
                if(!livrosEmprestimo.contains(livro))
                    model.addRow(new Object[]{livro.getCodLivro(), livro.getNome()});
            }
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUSelecionarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUSelecionarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUSelecionarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUSelecionarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btConfirmarEmprestimo;
    private javax.swing.JButton btPesquisarCod;
    private javax.swing.JButton btPesquisarNome;
    private javax.swing.JButton btRemove;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTable jTableLivrosEmprestimo;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextNome;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel model;
    private DefaultTableModel modelEmprestimo;
}
